version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: Docker/nginx
    restart: always
    ports:
      - 8888:9000
    depends_on:
      - vue

  vue:
    container_name: vue_app
    build:
      context: Docker/Vue
    restart: always
    volumes:
      - .:/app
    environment:
      TZ: Asia/Tokyo
    stdin_open: true
    tty: true

  spring:
    container_name: spring_app
    restart: always
    build:
      context: .
    ports:
      - 5000:8080